[workspace]

members = [
	"calorie_counting",
	"rock_paper_scissors",
	"rucksack_reorganization",
	"camp_cleanup",
	"supply_stacks",
	"tuning_trouble",
	"no_space_left_on_device",
	"tree_top_tree_house",
	"rope_bridge",
	"cathoderay_tube",
	"monkey_in_the_middle",
	"utils",
]
